### ISSUE TITLE
Plugin archetype and test environment

### ISSUE THREAD

**Issue by jkoenig134** [Manevolent/jbot#3]
Hi!
I wanted to hear about your test environment. How do you deploy the plugins to a manebot instance to test the functionalities?
And is it possible for you to provide a maven archetype for new plugins?

**Comment by Manevolent** [comment]
For the time being, I am deploying plugins for testing or internal purposes by configuring a custom internal Maven repository that I host on my own infrastructure.

There isn't a Maven archetype yet, but, I would like to make one.  For now, making a plug-in properties file and an "Entry" class is enough to get started writing a plug-in.
