### ISSUE TITLE
PostgreSQL Driver missing

### ISSUE THREAD

**Issue by jkoenig134** [Manevolent/jbot#4]
Your documentation at [here](https://github.com/Manebot/manebot/wiki/Docker-setup#setup-with-environment-variables) says, that the postgres driver is bundeled, but i get an `java.sql.SQLException: No suitable driver` exception for it.

**Comment by Manevolent** [comment]
I think you're absolutely right.  My bad.  I'll add that in as either a branch for the Docker container or bundle it all together.

**Comment by jkoenig134** [comment]
Thats great! Thank you!

**Comment by jkoenig134** [comment]
Hi @Manevolent! When do you plan to add the missing driver?

**Comment by Manevolent** [comment]
Hi @jkoenig134, thanks for the reminder; I can take care of this soon.  We'll see what it looks like, this should be straightforward.

**Comment by Manevolent** [comment]
I edited this in the pom.xml in this commit, only took a few seconds:

https://github.com/Manebot/manebot/commit/26f5e72b2dc79905d951cf66ceba484c13a839ad

**Comment by jkoenig134** [comment]
Thanks!
